# Config file for Air - Live Reload for Go

[build]
  bin = "app" # Binary name after build
  cmd = "go build -o ./tmp/main ." # Build command
  full_bin = "./tmp/main" # Full path to built binary
  dir = "." # Working directory
  exclude_dir = ["tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"] # Extensions to watch
  delay = 2000 # Delay in milliseconds before rebuilding after changes

[log]
  color = true # Colorize logs
  live_reload = false # Restart application on file changes
