# syntax=docker/dockerfile:1

# Step 1: Build the air binary
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Download Air
RUN go install github.com/air-verse/air@latest

# Step 2: Create the application image
FROM golang:1.22-alpine

WORKDIR /app

# Copy the air binary from the builder stage
COPY --from=builder /go/bin/air /usr/local/bin/air

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Command to run air
CMD ["air", "-c", ".air.toml"]
